-- Table Schemas
-- DROP TABLE IF EXISTS loans;
-- DROP TABLE IF EXISTS loan_results;
DROP TABLE IF EXISTS credit_applications;
DROP TABLE IF EXISTS credit_scores ;
DROP TABLE IF EXISTS customers ;
DROP TABLE  IF EXISTS user_roles;
DROP TABLE IF EXISTS users cascade ;
DROP TABLE IF EXISTS roles cascade;
CREATE TABLE users
(
    id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(25) UNIQUE NOT NULL,
    email    VARCHAR(25) UNIQUE NOT NULL,
    password VARCHAR(255)       NOT NULL
);

CREATE TABLE roles
(
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name varchar(10) UNIQUE NOT NULL
);
CREATE TABLE user_roles
(
    user_id INT NOT NULL,
    role_id INT NOT NULL,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE customers
(
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name     VARCHAR(25)        NOT NULL,
    last_name      VARCHAR(25)        NOT NULL,
    national_id    VARCHAR(11) UNIQUE NOT NULL,
    phone_number   VARCHAR(20)        NOT NULL,
    monthly_income INT                NOT NULL
-- email VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE credit_scores
(
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  INT NOT NULL,
    credit_score INT NOT NULL,
    FOREIGN KEY (customer_id) REFERENCES customers (id)
);

CREATE TABLE credit_applications
(
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id      INT         NOT NULL,
--  loan_score_id INT NOT NULL,
    credit_status    VARCHAR(10) NOT NULL,
    credit_limit     INT         NOT NULL,
    application_date DATE,
    FOREIGN KEY (customer_id) REFERENCES customers (id)
--  FOREIGN KEY(loan_score_id) REFERENCES loan_scores (id)
);

-- CREATE TABLE loan_results
-- (
--  id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--  loan_application_id INT NOT NULL,
--  loan_status VARCHAR(10) NOT NULL,
--  loan_limit INT NOT NULL,
--  loan_application_result_date DATE,
--   FOREIGN KEY(loan_application_id) REFERENCES loan_applications (id)
-- );

-- CREATE TABLE loans
-- (
-- id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
-- customer_id INT NOT NULL,
-- loan_limit  INT NOT NULL,
--  FOREIGN KEY(customer_id) REFERENCES customers (id)
-- );

INSERT INTO customers(first_name, last_name, national_id, phone_number, monthly_income)
VALUES ('Dale', 'Gomez', '81566338254', '81547833825', 5500),
       ('Andrew', 'Hooper', '22255942075', '2255942075', 4500),
       ('Ayanna', 'Mccall', '37956194325', '3795619325', 7000),
       ('Ian', 'Garisson', '16452443817', '16452436817', 8000),
       ('Phoebe', 'Cannon', '37467846746', '3746786746', 4250),
       ('Shelley', 'Cannon', '20762451322', '07624591322', 4250),
       ('Ashely', 'Garrison', '25409800111', '25408001111', 5500),
       ('Karina', 'Rose', '70884233185', '08842331835', 8800),
       ('Katell', 'Guzman', '30246143310', '02146143310', 3300),
       ('Ramona', 'Sawyer', '60800928532', '0800928532', 4600),
       ('Marvin', 'Rice', '73231501372', '7331501372', 9900),
       ('Lance', 'Ward', '17216582934', '17216829345', 10000),
       ('Xander', 'Gayer', '44815174144', '4485174144', 15000),
       ('Julian', 'Delacruz', '71511428297', '7151128297', 4250),
       ('Lamar', 'Valencia', '79116922864', '7911622864', 5500),
       ('Adam', 'Royce', '25879546321', '5061478596', 6000),
       ('Clark', 'Gould', '14587523698', '5426587412', 5000),
       ('Ivan', 'Eaten', '25469874152', '5421658596', 4250),
       ('Harrison', 'Walls', '14587965238', '5061487756', 9000),
       ('Lamar', 'Terrell', '58974125698', '5062147895', 5500);

INSERT INTO credit_scores(customer_id, credit_score)
VALUES (1, 420),
       (2, 340),
       (3, 500),
       (4, 750),
       (5, 200),
       (6, 880),
       (7, 950),
       (8, 340),
       (9, 790),
       (10, 660),
       (11, 1000),
       (12, 690),
       (13, 1200),
       (14, 1200),
       (15, 350),
       (16, 250),
       (17, 490),
       (18, 1000),
       (19, 1100),
       (20, 350);


INSERT INTO credit_applications(customer_id, credit_status, credit_limit, application_date)
VALUES (1, 'Rejected',0,'2022-02-12'),
       (2, 'Rejected',0,'2022-02-14'),
       (3, 'Approved',20000,'2022-02-14'),
       (4, 'Approved',20000,'2022-02-15'),
       (5, 'Rejected',0,'2022-02-15'),
       (6, 'Approved',10000,'2022-02-15'),
       (7, 'Approved',20000,'2022-02-15'),
       (8, 'Rejected',0,'2022-02-16'),
       (9, 'Approved',10000,'2022-02-16'),
       (10, 'Approved',10000,'2022-02-16'),
       (11, 'Approved',39600,'2022-02-16'),
       (12, 'Approved',20000,'2022-02-17'),
       (13, 'Approved',60000,'2022-02-18'),
       (14, 'Approved',17000,'2022-02-18'),
       (15, 'Rejected',0,'2022-02-18'),
       (16, 'Rejected',0,'2022-02-19'),
       (17, 'Rejected',0,'2022-02-19'),
       (18, 'Approved',17000,'2022-02-19'),
       (19, 'Approved',36000,'2022-02-20'),
       (20, 'Rejected',0,'2022-02-20');

INSERT INTO roles (role_name)
VALUES ('ROLE_ADMIN');
INSERT INTO roles (role_name)
VALUES ('ROLE_USER');