
-- Table Schemas
DROP TABLE IF EXISTS loans;
DROP TABLE IF EXISTS loan_results;
DROP TABLE IF EXISTS loan_applications;
DROP TABLE IF EXISTS loan_scores;
DROP TABLE IF EXISTS customers;

CREATE TABLE customers
(
 id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
first_name VARCHAR(25) NOT NULL,
last_name VARCHAR(25) NOT NULL,
identification_number VARCHAR(11) UNIQUE NOT NULL,
phone_number VARCHAR(20) NOT NULL,
monthly_income INT NOT NULL,
email VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE loan_scores
(
 id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 customer_id INT NOT NULL,
 loan_score INT NOT NULL,
FOREIGN KEY(customer_id) REFERENCES customers (id)
);

CREATE TABLE loan_applications
(
 id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 customer_id INT NOT NULL,
 loan_score_id INT NOT NULL,
 application_date DATE NOT NULL,
 FOREIGN KEY(customer_id) REFERENCES customers (id),
 FOREIGN KEY(loan_score_id) REFERENCES loan_scores (id)
);

CREATE TABLE loan_results
(
 id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 loan_application_id INT NOT NULL,
 loan_status VARCHAR(10) NOT NULL,
 loan_application_result_date DATE NOT NULL,
  FOREIGN KEY(loan_application_id) REFERENCES loan_applications (id)
);

CREATE TABLE loans
(
id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
customer_id INT NOT NULL,
loan_limit  INT NOT NULL,
 FOREIGN KEY(customer_id) REFERENCES customers (id)
);