
-- Table Schemas
DROP TABLE IF EXISTS loans;
DROP TABLE IF EXISTS loan_results;
DROP TABLE IF EXISTS loan_applications;
DROP TABLE IF EXISTS loan_scores;
DROP TABLE IF EXISTS customers;

CREATE TABLE customers
(
 id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
first_name VARCHAR(25) NOT NULL,
last_name VARCHAR(25) NOT NULL,
identification_number VARCHAR(11) UNIQUE NOT NULL,
phone_number VARCHAR(20) NOT NULL,
monthly_income INT NOT NULL
-- email VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE loan_scores
(
 id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 customer_id INT NOT NULL,
 loan_score INT NOT NULL,
FOREIGN KEY(customer_id) REFERENCES customers (id)
);

CREATE TABLE loan_applications
(
 id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 customer_id INT NOT NULL,
--  loan_score_id INT NOT NULL,
 loan_status VARCHAR(10) NOT NULL,
 loan_limit INT NOT NULL,
 FOREIGN KEY(customer_id) REFERENCES customers (id)
--  FOREIGN KEY(loan_score_id) REFERENCES loan_scores (id)
);

-- CREATE TABLE loan_results
-- (
--  id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--  loan_application_id INT NOT NULL,
--  loan_status VARCHAR(10) NOT NULL,
--  loan_limit INT NOT NULL,
--  loan_application_result_date DATE,
--   FOREIGN KEY(loan_application_id) REFERENCES loan_applications (id)
-- );

-- CREATE TABLE loans
-- (
-- id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
-- customer_id INT NOT NULL,
-- loan_limit  INT NOT NULL,
--  FOREIGN KEY(customer_id) REFERENCES customers (id)
-- );

-- INSERT INTO customers(first_name,last_name,identification_number,phone_number,monthly_income, email)
-- VALUES ('Dale', 'Gomez','81566338254','81547833825',5500,'mauris.blandit@outlook.org'),
--        ('Andrew', 'Hooper','22255942075','2255942075',4500,'semper.nam@protonmail.ca'),
--        ('Ayanna','Mccall','37956194325','3795619325',7000,'erat.volutpat@google.edu'),
--        ('Ian','Garisson','16452443817','16452436817',8000,'gravida.sit.amet@aol.com'),
--        ('Phoebe','Cannon','37467846746','3746786746',4250,'quisque.nonummy@hotmail.net'),
--        ('Shelley','Cannon','20762451322','07624591322',4250,'nunc.sed@outlook.couk'),
--        ('Ashely','Garrison','25409800111','25408001111',5500,'nec.metus@protonmail.edu'),
--        ('Karina','Rose','70884233185','08842331835',8800,'est.mollis@icloud.ca'),
--        ('Katell','Guzman','30246143310','02146143310',3300,'auctor.velit.aliquam@icloud.net'),
--        ('Ramona','Sawyer','60800928532','0800928532',4600,'adipiscing@yahoo.org'),
--        ('Marvin','Rice','73231501372','7331501372',9900,'marvin@aol.couk'),
--        ('Lance','Ward','17216582934','17216829345',10000,'lance7117@protonmail.edu'),
--        ('Xander','Gayer','44815174144','4485174144',15000,'xander1267@protonmail.org'),
--        ('Julian','Delacruz','71511428297','7151128297',4250,'julian@google.edu'),
--        ('Lamar','Valencia','79116922864','7911622864',5500,'lamar3853@outlook.com');

-- INSERT INTO loan_scores(customer_id, loan_score)
-- VALUES (1,2000);

--
-- INSERT INTO loan_applications(customer_id, loan_score_id)
-- VALUES (1,1)